{"level":"info","time":"2021-05-27 15:16:38","caller":"gin-use/main.go:43","msg":"傻逼日志不能调用","domain":"gin-use[fat]"}
{"level":"info","time":"2021-05-27 15:16:39","caller":"gin-use/main.go:43","msg":"傻逼日志不能调用","domain":"gin-use[fat]"}
{"level":"info","time":"2021-05-27 15:16:40","caller":"gin-use/main.go:43","msg":"傻逼日志不能调用","domain":"gin-use[fat]"}
{"level":"info","time":"2021-05-27 15:20:52","caller":"gin-use/main.go:43","msg":"傻逼日志不能调用","domain":"gin-use[fat]"}
{"level":"info","time":"2021-05-27 15:20:53","caller":"gin-use/main.go:43","msg":"傻逼日志不能调用","domain":"gin-use[fat]"}
{"level":"info","time":"2021-05-27 15:21:30","caller":"gin-use/main.go:43","msg":"傻逼日志不能调用","domain":"gin-use[fat]"}
{"level":"info","time":"2021-05-27 15:22:18","caller":"gin-use/main.go:43","msg":"傻逼日志怎么全局调用","domain":"gin-use[fat]"}
{"level":"info","time":"2021-05-27 15:24:24","caller":"gin-use/main.go:43","msg":"傻逼日志怎么全局调用","domain":"gin-use[fat]"}
{"level":"info","time":"2021-05-27 15:26:11","caller":"gin-use/main.go:43","msg":"傻逼日志怎么全局调用","domain":"gin-use[fat]"}
{"level":"info","time":"2021-05-27 15:45:40","caller":"gin-use/main.go:46","msg":"傻逼日志怎么全局调用","domain":"gin-use[fat]"}
{"level":"info","time":"2021-05-27 15:45:46","caller":"gin-use/main.go:46","msg":"傻逼日志怎么全局调用","domain":"gin-use[fat]"}
{"level":"info","time":"2021-05-27 15:45:47","caller":"gin-use/main.go:46","msg":"傻逼日志怎么全局调用","domain":"gin-use[fat]"}
{"level":"info","time":"2021-05-27 15:46:42","caller":"gin-use/main.go:46","msg":"傻逼日志怎么全局调用","domain":"gin-use[fat]"}
{"level":"info","time":"2021-05-27 15:46:43","caller":"gin-use/main.go:46","msg":"傻逼日志怎么全局调用","domain":"gin-use[fat]"}
{"level":"info","time":"2021-05-27 15:49:01","caller":"gin-use/main.go:46","msg":"傻逼日志怎么全局调用","domain":"gin-use[fat]"}
{"level":"info","time":"2021-05-27 15:49:05","caller":"gin-use/main.go:46","msg":"傻逼日志怎么全局调用","domain":"gin-use[fat]"}
{"level":"info","time":"2021-05-27 15:49:07","caller":"gin-use/main.go:46","msg":"傻逼日志怎么全局调用","domain":"gin-use[fat]"}
{"level":"info","time":"2021-05-27 15:49:22","caller":"gin-use/main.go:46","msg":"傻逼日志怎么全局调用","domain":"gin-use[fat]"}
{"level":"info","time":"2021-05-27 15:49:24","caller":"gin-use/main.go:46","msg":"傻逼日志怎么全局调用","domain":"gin-use[fat]"}
{"level":"info","time":"2021-05-27 15:50:07","caller":"gin-use/main.go:46","msg":"傻逼日志怎么全局调用","domain":"gin-use[fat]"}
{"level":"info","time":"2021-05-27 15:50:21","caller":"gin-use/main.go:46","msg":"傻逼日志怎么全局调用","domain":"gin-use[fat]"}
{"level":"info","time":"2021-05-27 15:50:23","caller":"controller/base.go:23","msg":"嘿，我能调用了","domain":"gin-use[fat]"}
{"level":"info","time":"2021-05-27 15:51:53","caller":"gin-use/main.go:47","msg":"傻逼日志怎么全局调用","domain":"gin-use[fat]"}
{"level":"error","time":"2021-05-27 16:36:06","caller":"gin-use/main.go:59","msg":"new db err","domain":"gin-use[fat]","error":"ping redis err: dial tcp 127.0.0.1:6379: connect: connection refused","errorVerbose":"dial tcp 127.0.0.1:6379: connect: connection refused\nping redis err\ngin-use/src/util/cache.redisConnect\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/cache/redis.go:71\ngin-use/src/util/cache.New\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/cache/redis.go:47\nmain.main\n\t/home/linkai/data/workspace/goWork/src/gin-use/main.go:57\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1373"}
{"level":"error","time":"2021-05-27 16:36:13","caller":"gin-use/main.go:59","msg":"new db err","domain":"gin-use[fat]","error":"ping redis err: dial tcp 127.0.0.1:6379: connect: connection refused","errorVerbose":"dial tcp 127.0.0.1:6379: connect: connection refused\nping redis err\ngin-use/src/util/cache.redisConnect\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/cache/redis.go:71\ngin-use/src/util/cache.New\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/cache/redis.go:47\nmain.main\n\t/home/linkai/data/workspace/goWork/src/gin-use/main.go:57\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1373"}
{"level":"error","time":"2021-05-27 16:36:20","caller":"gin-use/main.go:59","msg":"new db err","domain":"gin-use[fat]","error":"ping redis err: dial tcp 127.0.0.1:6379: connect: connection refused","errorVerbose":"dial tcp 127.0.0.1:6379: connect: connection refused\nping redis err\ngin-use/src/util/cache.redisConnect\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/cache/redis.go:71\ngin-use/src/util/cache.New\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/cache/redis.go:47\nmain.main\n\t/home/linkai/data/workspace/goWork/src/gin-use/main.go:57\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1373"}
{"level":"error","time":"2021-05-27 16:36:22","caller":"gin-use/main.go:59","msg":"new db err","domain":"gin-use[fat]","error":"ping redis err: dial tcp 127.0.0.1:6379: connect: connection refused","errorVerbose":"dial tcp 127.0.0.1:6379: connect: connection refused\nping redis err\ngin-use/src/util/cache.redisConnect\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/cache/redis.go:71\ngin-use/src/util/cache.New\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/cache/redis.go:47\nmain.main\n\t/home/linkai/data/workspace/goWork/src/gin-use/main.go:57\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1373"}
{"level":"info","time":"2021-05-27 17:08:29","caller":"controller/base.go:30","msg":"嘿，我能调用了","domain":"gin-use[fat]"}
{"level":"info","time":"2021-05-27 17:09:16","caller":"controller/base.go:30","msg":"嘿，我能调用了","domain":"gin-use[fat]"}
{"level":"info","time":"2021-05-27 17:09:55","caller":"controller/base.go:30","msg":"嘿，我能调用了","domain":"gin-use[fat]"}
{"level":"info","time":"2021-05-27 17:41:04","caller":"controller/base.go:31","msg":"嘿，我能调用了","domain":"gin-use[fat]"}
{"level":"info","time":"2021-05-27 17:41:30","caller":"controller/base.go:31","msg":"嘿，我能调用了","domain":"gin-use[fat]"}
{"level":"info","time":"2021-05-27 17:44:27","caller":"controller/base.go:31","msg":"嘿，我能调用了","domain":"gin-use[fat]"}
{"level":"info","time":"2021-05-28 10:08:50","caller":"controller/base.go:31","msg":"嘿，我能调用了","domain":"gin-use[fat]"}
{"level":"info","time":"2021-05-28 11:50:31","caller":"controller/base.go:31","msg":"嘿，我能调用了","domain":"gin-use[fat]"}
{"level":"info","time":"2021-05-28 13:59:19","caller":"controller/base.go:32","msg":"嘿，我能调用了","domain":"gin-use[fat]"}
{"level":"info","time":"2021-05-28 14:02:56","caller":"controller/base.go:32","msg":"嘿，我能调用了","domain":"gin-use[fat]"}
{"level":"info","time":"2021-05-28 14:38:29","caller":"controller/base.go:32","msg":"嘿，我能调用了","domain":"gin-use[fat]"}
{"level":"info","time":"2021-05-28 14:39:39","caller":"controller/base.go:32","msg":"嘿，我能调用了","domain":"gin-use[fat]"}
{"level":"info","time":"2021-05-28 14:39:40","caller":"controller/base.go:32","msg":"嘿，我能调用了","domain":"gin-use[fat]"}
{"level":"info","time":"2021-05-28 14:39:40","caller":"controller/base.go:32","msg":"嘿，我能调用了","domain":"gin-use[fat]"}
{"level":"info","time":"2021-05-28 14:39:41","caller":"controller/base.go:32","msg":"嘿，我能调用了","domain":"gin-use[fat]"}
{"level":"info","time":"2021-05-28 14:39:41","caller":"controller/base.go:32","msg":"嘿，我能调用了","domain":"gin-use[fat]"}
{"level":"info","time":"2021-05-28 14:39:41","caller":"controller/base.go:32","msg":"嘿，我能调用了","domain":"gin-use[fat]"}
{"level":"info","time":"2021-05-28 14:39:42","caller":"controller/base.go:32","msg":"嘿，我能调用了","domain":"gin-use[fat]"}
{"level":"info","time":"2021-05-28 14:39:42","caller":"controller/base.go:32","msg":"嘿，我能调用了","domain":"gin-use[fat]"}
{"level":"info","time":"2021-05-28 14:39:42","caller":"controller/base.go:32","msg":"嘿，我能调用了","domain":"gin-use[fat]"}
{"level":"info","time":"2021-05-28 14:41:11","caller":"controller/base.go:32","msg":"嘿，我能调用了","domain":"gin-use[fat]"}
{"level":"error","time":"2021-05-29 17:01:23","caller":"gin-use/main.go:49","msg":"new db err","domain":"gin-use[fat]","error":"[db connection failed] Database name: : failed to connect to `host=port= user=password= database=sslmode=disable`: hostname resolving error (lookup port=: no such host)","errorVerbose":"failed to connect to `host=port= user=password= database=sslmode=disable`: hostname resolving error (lookup port=: no such host)\n[db connection failed] Database name: \ngin-use/src/util/db.dbConnect\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/db/postgres.go:83\ngin-use/src/util/db.New\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/db/postgres.go:30\nmain.main\n\t/home/linkai/data/workspace/goWork/src/gin-use/main.go:47\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1373"}
{"level":"error","time":"2021-05-29 17:01:23","caller":"gin-use/main.go:56","msg":"new cahe err","domain":"gin-use[fat]","error":"ping redis err: dial tcp 127.0.0.1:6379: connect: connection refused","errorVerbose":"dial tcp 127.0.0.1:6379: connect: connection refused\nping redis err\ngin-use/src/util/cache.redisConnect\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/cache/redis.go:71\ngin-use/src/util/cache.New\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/cache/redis.go:47\nmain.main\n\t/home/linkai/data/workspace/goWork/src/gin-use/main.go:54\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1373"}
{"level":"error","time":"2021-05-29 17:04:00","caller":"gin-use/main.go:49","msg":"new db err","domain":"gin-use[fat]","error":"[db connection failed] Database name: : failed to connect to `host=port= user=password= database=sslmode=disable`: hostname resolving error (lookup port=: no such host)","errorVerbose":"failed to connect to `host=port= user=password= database=sslmode=disable`: hostname resolving error (lookup port=: no such host)\n[db connection failed] Database name: \ngin-use/src/util/db.dbConnect\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/db/postgres.go:83\ngin-use/src/util/db.New\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/db/postgres.go:30\nmain.main\n\t/home/linkai/data/workspace/goWork/src/gin-use/main.go:47\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1373"}
{"level":"error","time":"2021-05-29 17:04:00","caller":"gin-use/main.go:56","msg":"new cahe err","domain":"gin-use[fat]","error":"ping redis err: dial tcp 127.0.0.1:6379: connect: connection refused","errorVerbose":"dial tcp 127.0.0.1:6379: connect: connection refused\nping redis err\ngin-use/src/util/cache.redisConnect\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/cache/redis.go:71\ngin-use/src/util/cache.New\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/cache/redis.go:47\nmain.main\n\t/home/linkai/data/workspace/goWork/src/gin-use/main.go:54\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1373"}
{"level":"error","time":"2021-05-29 17:05:35","caller":"gin-use/main.go:49","msg":"new db err","domain":"gin-use[fat]","error":"[db connection failed] Database name: : failed to connect to `host=port= user=password= database=sslmode=disable`: hostname resolving error (lookup port=: no such host)","errorVerbose":"failed to connect to `host=port= user=password= database=sslmode=disable`: hostname resolving error (lookup port=: no such host)\n[db connection failed] Database name: \ngin-use/src/util/db.dbConnect\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/db/postgres.go:83\ngin-use/src/util/db.New\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/db/postgres.go:30\nmain.main\n\t/home/linkai/data/workspace/goWork/src/gin-use/main.go:47\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1373"}
{"level":"error","time":"2021-05-29 17:05:35","caller":"gin-use/main.go:56","msg":"new cahe err","domain":"gin-use[fat]","error":"ping redis err: dial tcp 127.0.0.1:6379: connect: connection refused","errorVerbose":"dial tcp 127.0.0.1:6379: connect: connection refused\nping redis err\ngin-use/src/util/cache.redisConnect\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/cache/redis.go:71\ngin-use/src/util/cache.New\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/cache/redis.go:47\nmain.main\n\t/home/linkai/data/workspace/goWork/src/gin-use/main.go:54\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1373"}
{"level":"error","time":"2021-05-29 17:32:42","caller":"gin-use/main.go:49","msg":"new db err","domain":"gin-use[fat]","error":"[db connection failed] Database name: : failed to connect to `host=port= user=password= database=sslmode=disable`: hostname resolving error (lookup port=: no such host)","errorVerbose":"failed to connect to `host=port= user=password= database=sslmode=disable`: hostname resolving error (lookup port=: no such host)\n[db connection failed] Database name: \ngin-use/src/util/db.dbConnect\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/db/postgres.go:83\ngin-use/src/util/db.New\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/db/postgres.go:30\nmain.main\n\t/home/linkai/data/workspace/goWork/src/gin-use/main.go:47\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"}
{"level":"error","time":"2021-05-29 17:32:42","caller":"gin-use/main.go:56","msg":"new cahe err","domain":"gin-use[fat]","error":"ping redis err: dial tcp 127.0.0.1:6379: connect: connection refused","errorVerbose":"dial tcp 127.0.0.1:6379: connect: connection refused\nping redis err\ngin-use/src/util/cache.redisConnect\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/cache/redis.go:71\ngin-use/src/util/cache.New\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/cache/redis.go:47\nmain.main\n\t/home/linkai/data/workspace/goWork/src/gin-use/main.go:54\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"}
{"level":"error","time":"2021-06-01 14:57:36","caller":"gin-use/main.go:49","msg":"new db err","domain":"gin-use[dev]","error":"[db connection failed] Database name: : failed to connect to `host=port= user=password= database=sslmode=disable`: hostname resolving error (lookup port=: no such host)","errorVerbose":"failed to connect to `host=port= user=password= database=sslmode=disable`: hostname resolving error (lookup port=: no such host)\n[db connection failed] Database name: \ngin-use/src/util/db.dbConnect\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/db/postgres.go:83\ngin-use/src/util/db.New\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/db/postgres.go:30\nmain.main\n\t/home/linkai/data/workspace/goWork/src/gin-use/main.go:47\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"}
{"level":"error","time":"2021-06-01 14:57:36","caller":"gin-use/main.go:56","msg":"new cahe err","domain":"gin-use[dev]","error":"ping redis err: dial tcp 127.0.0.1:6379: connect: connection refused","errorVerbose":"dial tcp 127.0.0.1:6379: connect: connection refused\nping redis err\ngin-use/src/util/cache.redisConnect\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/cache/redis.go:71\ngin-use/src/util/cache.New\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/cache/redis.go:47\nmain.main\n\t/home/linkai/data/workspace/goWork/src/gin-use/main.go:54\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"}
{"level":"error","time":"2021-06-01 14:57:39","caller":"gin-use/main.go:49","msg":"new db err","domain":"gin-use[dev]","error":"[db connection failed] Database name: : failed to connect to `host=port= user=password= database=sslmode=disable`: hostname resolving error (lookup port=: no such host)","errorVerbose":"failed to connect to `host=port= user=password= database=sslmode=disable`: hostname resolving error (lookup port=: no such host)\n[db connection failed] Database name: \ngin-use/src/util/db.dbConnect\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/db/postgres.go:83\ngin-use/src/util/db.New\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/db/postgres.go:30\nmain.main\n\t/home/linkai/data/workspace/goWork/src/gin-use/main.go:47\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"}
{"level":"error","time":"2021-06-01 14:57:40","caller":"gin-use/main.go:56","msg":"new cahe err","domain":"gin-use[dev]","error":"ping redis err: dial tcp 127.0.0.1:6379: connect: connection refused","errorVerbose":"dial tcp 127.0.0.1:6379: connect: connection refused\nping redis err\ngin-use/src/util/cache.redisConnect\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/cache/redis.go:71\ngin-use/src/util/cache.New\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/cache/redis.go:47\nmain.main\n\t/home/linkai/data/workspace/goWork/src/gin-use/main.go:54\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"}
{"level":"error","time":"2021-06-01 14:57:44","caller":"gin-use/main.go:49","msg":"new db err","domain":"gin-use[dev]","error":"[db connection failed] Database name: : failed to connect to `host=port= user=password= database=sslmode=disable`: hostname resolving error (lookup port=: no such host)","errorVerbose":"failed to connect to `host=port= user=password= database=sslmode=disable`: hostname resolving error (lookup port=: no such host)\n[db connection failed] Database name: \ngin-use/src/util/db.dbConnect\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/db/postgres.go:83\ngin-use/src/util/db.New\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/db/postgres.go:30\nmain.main\n\t/home/linkai/data/workspace/goWork/src/gin-use/main.go:47\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"}
{"level":"error","time":"2021-06-01 14:57:44","caller":"gin-use/main.go:56","msg":"new cahe err","domain":"gin-use[dev]","error":"ping redis err: dial tcp 127.0.0.1:6379: connect: connection refused","errorVerbose":"dial tcp 127.0.0.1:6379: connect: connection refused\nping redis err\ngin-use/src/util/cache.redisConnect\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/cache/redis.go:71\ngin-use/src/util/cache.New\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/cache/redis.go:47\nmain.main\n\t/home/linkai/data/workspace/goWork/src/gin-use/main.go:54\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"}
{"level":"error","time":"2021-06-01 14:57:46","caller":"gin-use/main.go:49","msg":"new db err","domain":"gin-use[dev]","error":"[db connection failed] Database name: : failed to connect to `host=port= user=password= database=sslmode=disable`: hostname resolving error (lookup port=: no such host)","errorVerbose":"failed to connect to `host=port= user=password= database=sslmode=disable`: hostname resolving error (lookup port=: no such host)\n[db connection failed] Database name: \ngin-use/src/util/db.dbConnect\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/db/postgres.go:83\ngin-use/src/util/db.New\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/db/postgres.go:30\nmain.main\n\t/home/linkai/data/workspace/goWork/src/gin-use/main.go:47\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"}
{"level":"error","time":"2021-06-01 14:57:46","caller":"gin-use/main.go:56","msg":"new cahe err","domain":"gin-use[dev]","error":"ping redis err: dial tcp 127.0.0.1:6379: connect: connection refused","errorVerbose":"dial tcp 127.0.0.1:6379: connect: connection refused\nping redis err\ngin-use/src/util/cache.redisConnect\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/cache/redis.go:71\ngin-use/src/util/cache.New\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/cache/redis.go:47\nmain.main\n\t/home/linkai/data/workspace/goWork/src/gin-use/main.go:54\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"}
{"level":"error","time":"2021-06-01 14:57:52","caller":"gin-use/main.go:49","msg":"new db err","domain":"gin-use[dev]","error":"[db connection failed] Database name: : failed to connect to `host=port= user=password= database=sslmode=disable`: hostname resolving error (lookup port=: no such host)","errorVerbose":"failed to connect to `host=port= user=password= database=sslmode=disable`: hostname resolving error (lookup port=: no such host)\n[db connection failed] Database name: \ngin-use/src/util/db.dbConnect\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/db/postgres.go:83\ngin-use/src/util/db.New\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/db/postgres.go:30\nmain.main\n\t/home/linkai/data/workspace/goWork/src/gin-use/main.go:47\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"}
{"level":"error","time":"2021-06-01 14:57:52","caller":"gin-use/main.go:56","msg":"new cahe err","domain":"gin-use[dev]","error":"ping redis err: dial tcp 127.0.0.1:6379: connect: connection refused","errorVerbose":"dial tcp 127.0.0.1:6379: connect: connection refused\nping redis err\ngin-use/src/util/cache.redisConnect\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/cache/redis.go:71\ngin-use/src/util/cache.New\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/cache/redis.go:47\nmain.main\n\t/home/linkai/data/workspace/goWork/src/gin-use/main.go:54\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"}
{"level":"error","time":"2021-06-01 14:58:04","caller":"gin-use/main.go:49","msg":"new db err","domain":"gin-use[dev]","error":"[db connection failed] Database name: : failed to connect to `host=port= user=password= database=sslmode=disable`: hostname resolving error (lookup port=: no such host)","errorVerbose":"failed to connect to `host=port= user=password= database=sslmode=disable`: hostname resolving error (lookup port=: no such host)\n[db connection failed] Database name: \ngin-use/src/util/db.dbConnect\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/db/postgres.go:83\ngin-use/src/util/db.New\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/db/postgres.go:30\nmain.main\n\t/home/linkai/data/workspace/goWork/src/gin-use/main.go:47\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"}
{"level":"error","time":"2021-06-01 14:58:04","caller":"gin-use/main.go:56","msg":"new cahe err","domain":"gin-use[dev]","error":"ping redis err: dial tcp 127.0.0.1:6379: connect: connection refused","errorVerbose":"dial tcp 127.0.0.1:6379: connect: connection refused\nping redis err\ngin-use/src/util/cache.redisConnect\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/cache/redis.go:71\ngin-use/src/util/cache.New\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/cache/redis.go:47\nmain.main\n\t/home/linkai/data/workspace/goWork/src/gin-use/main.go:54\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"}
{"level":"error","time":"2021-06-01 14:58:09","caller":"gin-use/main.go:49","msg":"new db err","domain":"gin-use[dev]","error":"[db connection failed] Database name: : failed to connect to `host=port= user=password= database=sslmode=disable`: hostname resolving error (lookup port=: no such host)","errorVerbose":"failed to connect to `host=port= user=password= database=sslmode=disable`: hostname resolving error (lookup port=: no such host)\n[db connection failed] Database name: \ngin-use/src/util/db.dbConnect\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/db/postgres.go:83\ngin-use/src/util/db.New\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/db/postgres.go:30\nmain.main\n\t/home/linkai/data/workspace/goWork/src/gin-use/main.go:47\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"}
{"level":"error","time":"2021-06-01 14:58:09","caller":"gin-use/main.go:56","msg":"new cahe err","domain":"gin-use[dev]","error":"ping redis err: dial tcp 127.0.0.1:6379: connect: connection refused","errorVerbose":"dial tcp 127.0.0.1:6379: connect: connection refused\nping redis err\ngin-use/src/util/cache.redisConnect\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/cache/redis.go:71\ngin-use/src/util/cache.New\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/cache/redis.go:47\nmain.main\n\t/home/linkai/data/workspace/goWork/src/gin-use/main.go:54\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"}
{"level":"error","time":"2021-06-01 14:58:10","caller":"gin-use/main.go:49","msg":"new db err","domain":"gin-use[dev]","error":"[db connection failed] Database name: : failed to connect to `host=port= user=password= database=sslmode=disable`: hostname resolving error (lookup port=: no such host)","errorVerbose":"failed to connect to `host=port= user=password= database=sslmode=disable`: hostname resolving error (lookup port=: no such host)\n[db connection failed] Database name: \ngin-use/src/util/db.dbConnect\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/db/postgres.go:83\ngin-use/src/util/db.New\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/db/postgres.go:30\nmain.main\n\t/home/linkai/data/workspace/goWork/src/gin-use/main.go:47\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"}
{"level":"error","time":"2021-06-01 14:58:10","caller":"gin-use/main.go:56","msg":"new cahe err","domain":"gin-use[dev]","error":"ping redis err: dial tcp 127.0.0.1:6379: connect: connection refused","errorVerbose":"dial tcp 127.0.0.1:6379: connect: connection refused\nping redis err\ngin-use/src/util/cache.redisConnect\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/cache/redis.go:71\ngin-use/src/util/cache.New\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/cache/redis.go:47\nmain.main\n\t/home/linkai/data/workspace/goWork/src/gin-use/main.go:54\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"}
{"level":"error","time":"2021-06-01 14:58:32","caller":"gin-use/main.go:49","msg":"new db err","domain":"gin-use[dev]","error":"[db connection failed] Database name: : failed to connect to `host=port= user=password= database=sslmode=disable`: hostname resolving error (lookup port=: no such host)","errorVerbose":"failed to connect to `host=port= user=password= database=sslmode=disable`: hostname resolving error (lookup port=: no such host)\n[db connection failed] Database name: \ngin-use/src/util/db.dbConnect\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/db/postgres.go:83\ngin-use/src/util/db.New\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/db/postgres.go:30\nmain.main\n\t/home/linkai/data/workspace/goWork/src/gin-use/main.go:47\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"}
{"level":"error","time":"2021-06-01 14:58:32","caller":"gin-use/main.go:56","msg":"new cahe err","domain":"gin-use[dev]","error":"ping redis err: dial tcp 127.0.0.1:6379: connect: connection refused","errorVerbose":"dial tcp 127.0.0.1:6379: connect: connection refused\nping redis err\ngin-use/src/util/cache.redisConnect\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/cache/redis.go:71\ngin-use/src/util/cache.New\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/cache/redis.go:47\nmain.main\n\t/home/linkai/data/workspace/goWork/src/gin-use/main.go:54\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"}
{"level":"error","time":"2021-06-01 14:58:42","caller":"gin-use/main.go:49","msg":"new db err","domain":"gin-use[dev]","error":"[db connection failed] Database name: : failed to connect to `host=port= user=password= database=sslmode=disable`: hostname resolving error (lookup port=: no such host)","errorVerbose":"failed to connect to `host=port= user=password= database=sslmode=disable`: hostname resolving error (lookup port=: no such host)\n[db connection failed] Database name: \ngin-use/src/util/db.dbConnect\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/db/postgres.go:83\ngin-use/src/util/db.New\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/db/postgres.go:30\nmain.main\n\t/home/linkai/data/workspace/goWork/src/gin-use/main.go:47\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"}
{"level":"error","time":"2021-06-01 14:58:42","caller":"gin-use/main.go:56","msg":"new cahe err","domain":"gin-use[dev]","error":"ping redis err: dial tcp 127.0.0.1:6379: connect: connection refused","errorVerbose":"dial tcp 127.0.0.1:6379: connect: connection refused\nping redis err\ngin-use/src/util/cache.redisConnect\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/cache/redis.go:71\ngin-use/src/util/cache.New\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/cache/redis.go:47\nmain.main\n\t/home/linkai/data/workspace/goWork/src/gin-use/main.go:54\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"}
{"level":"error","time":"2021-06-01 14:58:51","caller":"gin-use/main.go:49","msg":"new db err","domain":"gin-use[dev]","error":"[db connection failed] Database name: : failed to connect to `host=port= user=password= database=sslmode=disable`: hostname resolving error (lookup port=: no such host)","errorVerbose":"failed to connect to `host=port= user=password= database=sslmode=disable`: hostname resolving error (lookup port=: no such host)\n[db connection failed] Database name: \ngin-use/src/util/db.dbConnect\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/db/postgres.go:83\ngin-use/src/util/db.New\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/db/postgres.go:30\nmain.main\n\t/home/linkai/data/workspace/goWork/src/gin-use/main.go:47\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"}
{"level":"error","time":"2021-06-01 14:58:51","caller":"gin-use/main.go:56","msg":"new cahe err","domain":"gin-use[dev]","error":"ping redis err: dial tcp 127.0.0.1:6379: connect: connection refused","errorVerbose":"dial tcp 127.0.0.1:6379: connect: connection refused\nping redis err\ngin-use/src/util/cache.redisConnect\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/cache/redis.go:71\ngin-use/src/util/cache.New\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/cache/redis.go:47\nmain.main\n\t/home/linkai/data/workspace/goWork/src/gin-use/main.go:54\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"}
{"level":"error","time":"2021-06-01 14:58:57","caller":"gin-use/main.go:49","msg":"new db err","domain":"gin-use[dev]","error":"[db connection failed] Database name: : failed to connect to `host=port= user=password= database=sslmode=disable`: hostname resolving error (lookup port=: no such host)","errorVerbose":"failed to connect to `host=port= user=password= database=sslmode=disable`: hostname resolving error (lookup port=: no such host)\n[db connection failed] Database name: \ngin-use/src/util/db.dbConnect\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/db/postgres.go:83\ngin-use/src/util/db.New\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/db/postgres.go:30\nmain.main\n\t/home/linkai/data/workspace/goWork/src/gin-use/main.go:47\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"}
{"level":"error","time":"2021-06-01 14:58:57","caller":"gin-use/main.go:56","msg":"new cahe err","domain":"gin-use[dev]","error":"ping redis err: dial tcp 127.0.0.1:6379: connect: connection refused","errorVerbose":"dial tcp 127.0.0.1:6379: connect: connection refused\nping redis err\ngin-use/src/util/cache.redisConnect\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/cache/redis.go:71\ngin-use/src/util/cache.New\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/cache/redis.go:47\nmain.main\n\t/home/linkai/data/workspace/goWork/src/gin-use/main.go:54\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"}
{"level":"error","time":"2021-06-01 14:59:00","caller":"gin-use/main.go:49","msg":"new db err","domain":"gin-use[dev]","error":"[db connection failed] Database name: : failed to connect to `host=port= user=password= database=sslmode=disable`: hostname resolving error (lookup port=: no such host)","errorVerbose":"failed to connect to `host=port= user=password= database=sslmode=disable`: hostname resolving error (lookup port=: no such host)\n[db connection failed] Database name: \ngin-use/src/util/db.dbConnect\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/db/postgres.go:83\ngin-use/src/util/db.New\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/db/postgres.go:30\nmain.main\n\t/home/linkai/data/workspace/goWork/src/gin-use/main.go:47\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"}
{"level":"error","time":"2021-06-01 14:59:00","caller":"gin-use/main.go:56","msg":"new cahe err","domain":"gin-use[dev]","error":"ping redis err: dial tcp 127.0.0.1:6379: connect: connection refused","errorVerbose":"dial tcp 127.0.0.1:6379: connect: connection refused\nping redis err\ngin-use/src/util/cache.redisConnect\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/cache/redis.go:71\ngin-use/src/util/cache.New\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/cache/redis.go:47\nmain.main\n\t/home/linkai/data/workspace/goWork/src/gin-use/main.go:54\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"}
{"level":"error","time":"2021-06-01 14:59:06","caller":"gin-use/main.go:49","msg":"new db err","domain":"gin-use[dev]","error":"[db connection failed] Database name: : failed to connect to `host=port= user=password= database=sslmode=disable`: hostname resolving error (lookup port=: no such host)","errorVerbose":"failed to connect to `host=port= user=password= database=sslmode=disable`: hostname resolving error (lookup port=: no such host)\n[db connection failed] Database name: \ngin-use/src/util/db.dbConnect\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/db/postgres.go:83\ngin-use/src/util/db.New\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/db/postgres.go:30\nmain.main\n\t/home/linkai/data/workspace/goWork/src/gin-use/main.go:47\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"}
{"level":"error","time":"2021-06-01 14:59:06","caller":"gin-use/main.go:56","msg":"new cahe err","domain":"gin-use[dev]","error":"ping redis err: dial tcp 127.0.0.1:6379: connect: connection refused","errorVerbose":"dial tcp 127.0.0.1:6379: connect: connection refused\nping redis err\ngin-use/src/util/cache.redisConnect\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/cache/redis.go:71\ngin-use/src/util/cache.New\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/cache/redis.go:47\nmain.main\n\t/home/linkai/data/workspace/goWork/src/gin-use/main.go:54\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"}
{"level":"error","time":"2021-06-01 14:59:08","caller":"gin-use/main.go:49","msg":"new db err","domain":"gin-use[dev]","error":"[db connection failed] Database name: : failed to connect to `host=port= user=password= database=sslmode=disable`: hostname resolving error (lookup port=: no such host)","errorVerbose":"failed to connect to `host=port= user=password= database=sslmode=disable`: hostname resolving error (lookup port=: no such host)\n[db connection failed] Database name: \ngin-use/src/util/db.dbConnect\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/db/postgres.go:83\ngin-use/src/util/db.New\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/db/postgres.go:30\nmain.main\n\t/home/linkai/data/workspace/goWork/src/gin-use/main.go:47\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"}
{"level":"error","time":"2021-06-01 14:59:08","caller":"gin-use/main.go:56","msg":"new cahe err","domain":"gin-use[dev]","error":"ping redis err: dial tcp 127.0.0.1:6379: connect: connection refused","errorVerbose":"dial tcp 127.0.0.1:6379: connect: connection refused\nping redis err\ngin-use/src/util/cache.redisConnect\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/cache/redis.go:71\ngin-use/src/util/cache.New\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/cache/redis.go:47\nmain.main\n\t/home/linkai/data/workspace/goWork/src/gin-use/main.go:54\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"}
{"level":"error","time":"2021-06-01 14:59:15","caller":"gin-use/main.go:49","msg":"new db err","domain":"gin-use[dev]","error":"[db connection failed] Database name: : failed to connect to `host=port= user=password= database=sslmode=disable`: hostname resolving error (lookup port=: no such host)","errorVerbose":"failed to connect to `host=port= user=password= database=sslmode=disable`: hostname resolving error (lookup port=: no such host)\n[db connection failed] Database name: \ngin-use/src/util/db.dbConnect\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/db/postgres.go:83\ngin-use/src/util/db.New\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/db/postgres.go:30\nmain.main\n\t/home/linkai/data/workspace/goWork/src/gin-use/main.go:47\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"}
{"level":"error","time":"2021-06-01 14:59:15","caller":"gin-use/main.go:56","msg":"new cahe err","domain":"gin-use[dev]","error":"ping redis err: dial tcp 127.0.0.1:6379: connect: connection refused","errorVerbose":"dial tcp 127.0.0.1:6379: connect: connection refused\nping redis err\ngin-use/src/util/cache.redisConnect\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/cache/redis.go:71\ngin-use/src/util/cache.New\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/cache/redis.go:47\nmain.main\n\t/home/linkai/data/workspace/goWork/src/gin-use/main.go:54\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"}
{"level":"error","time":"2021-06-01 14:59:29","caller":"gin-use/main.go:49","msg":"new db err","domain":"gin-use[dev]","error":"[db connection failed] Database name: : failed to connect to `host=port= user=password= database=sslmode=disable`: hostname resolving error (lookup port=: no such host)","errorVerbose":"failed to connect to `host=port= user=password= database=sslmode=disable`: hostname resolving error (lookup port=: no such host)\n[db connection failed] Database name: \ngin-use/src/util/db.dbConnect\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/db/postgres.go:83\ngin-use/src/util/db.New\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/db/postgres.go:30\nmain.main\n\t/home/linkai/data/workspace/goWork/src/gin-use/main.go:47\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"}
{"level":"error","time":"2021-06-01 14:59:29","caller":"gin-use/main.go:56","msg":"new cahe err","domain":"gin-use[dev]","error":"ping redis err: dial tcp 127.0.0.1:6379: connect: connection refused","errorVerbose":"dial tcp 127.0.0.1:6379: connect: connection refused\nping redis err\ngin-use/src/util/cache.redisConnect\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/cache/redis.go:71\ngin-use/src/util/cache.New\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/cache/redis.go:47\nmain.main\n\t/home/linkai/data/workspace/goWork/src/gin-use/main.go:54\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"}
{"level":"error","time":"2021-06-01 14:59:34","caller":"gin-use/main.go:49","msg":"new db err","domain":"gin-use[dev]","error":"[db connection failed] Database name: : failed to connect to `host=port= user=password= database=sslmode=disable`: hostname resolving error (lookup port=: no such host)","errorVerbose":"failed to connect to `host=port= user=password= database=sslmode=disable`: hostname resolving error (lookup port=: no such host)\n[db connection failed] Database name: \ngin-use/src/util/db.dbConnect\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/db/postgres.go:83\ngin-use/src/util/db.New\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/db/postgres.go:30\nmain.main\n\t/home/linkai/data/workspace/goWork/src/gin-use/main.go:47\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"}
{"level":"error","time":"2021-06-01 14:59:34","caller":"gin-use/main.go:56","msg":"new cahe err","domain":"gin-use[dev]","error":"ping redis err: dial tcp 127.0.0.1:6379: connect: connection refused","errorVerbose":"dial tcp 127.0.0.1:6379: connect: connection refused\nping redis err\ngin-use/src/util/cache.redisConnect\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/cache/redis.go:71\ngin-use/src/util/cache.New\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/cache/redis.go:47\nmain.main\n\t/home/linkai/data/workspace/goWork/src/gin-use/main.go:54\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"}
{"level":"error","time":"2021-06-01 14:59:38","caller":"gin-use/main.go:49","msg":"new db err","domain":"gin-use[dev]","error":"[db connection failed] Database name: : failed to connect to `host=port= user=password= database=sslmode=disable`: hostname resolving error (lookup port=: no such host)","errorVerbose":"failed to connect to `host=port= user=password= database=sslmode=disable`: hostname resolving error (lookup port=: no such host)\n[db connection failed] Database name: \ngin-use/src/util/db.dbConnect\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/db/postgres.go:83\ngin-use/src/util/db.New\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/db/postgres.go:30\nmain.main\n\t/home/linkai/data/workspace/goWork/src/gin-use/main.go:47\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"}
{"level":"error","time":"2021-06-01 14:59:38","caller":"gin-use/main.go:56","msg":"new cahe err","domain":"gin-use[dev]","error":"ping redis err: dial tcp 127.0.0.1:6379: connect: connection refused","errorVerbose":"dial tcp 127.0.0.1:6379: connect: connection refused\nping redis err\ngin-use/src/util/cache.redisConnect\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/cache/redis.go:71\ngin-use/src/util/cache.New\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/cache/redis.go:47\nmain.main\n\t/home/linkai/data/workspace/goWork/src/gin-use/main.go:54\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"}
{"level":"error","time":"2021-06-01 15:00:04","caller":"gin-use/main.go:49","msg":"new db err","domain":"gin-use[dev]","error":"[db connection failed] Database name: : failed to connect to `host=port= user=password= database=sslmode=disable`: hostname resolving error (lookup port=: no such host)","errorVerbose":"failed to connect to `host=port= user=password= database=sslmode=disable`: hostname resolving error (lookup port=: no such host)\n[db connection failed] Database name: \ngin-use/src/util/db.dbConnect\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/db/postgres.go:83\ngin-use/src/util/db.New\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/db/postgres.go:30\nmain.main\n\t/home/linkai/data/workspace/goWork/src/gin-use/main.go:47\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"}
{"level":"error","time":"2021-06-01 15:00:04","caller":"gin-use/main.go:56","msg":"new cahe err","domain":"gin-use[dev]","error":"ping redis err: dial tcp 127.0.0.1:6379: connect: connection refused","errorVerbose":"dial tcp 127.0.0.1:6379: connect: connection refused\nping redis err\ngin-use/src/util/cache.redisConnect\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/cache/redis.go:71\ngin-use/src/util/cache.New\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/cache/redis.go:47\nmain.main\n\t/home/linkai/data/workspace/goWork/src/gin-use/main.go:54\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"}
{"level":"error","time":"2021-06-01 15:00:07","caller":"gin-use/main.go:49","msg":"new db err","domain":"gin-use[dev]","error":"[db connection failed] Database name: : failed to connect to `host=port= user=password= database=sslmode=disable`: hostname resolving error (lookup port=: no such host)","errorVerbose":"failed to connect to `host=port= user=password= database=sslmode=disable`: hostname resolving error (lookup port=: no such host)\n[db connection failed] Database name: \ngin-use/src/util/db.dbConnect\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/db/postgres.go:83\ngin-use/src/util/db.New\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/db/postgres.go:30\nmain.main\n\t/home/linkai/data/workspace/goWork/src/gin-use/main.go:47\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"}
{"level":"error","time":"2021-06-01 15:00:07","caller":"gin-use/main.go:56","msg":"new cahe err","domain":"gin-use[dev]","error":"ping redis err: dial tcp 127.0.0.1:6379: connect: connection refused","errorVerbose":"dial tcp 127.0.0.1:6379: connect: connection refused\nping redis err\ngin-use/src/util/cache.redisConnect\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/cache/redis.go:71\ngin-use/src/util/cache.New\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/cache/redis.go:47\nmain.main\n\t/home/linkai/data/workspace/goWork/src/gin-use/main.go:54\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"}
{"level":"error","time":"2021-06-01 15:00:14","caller":"gin-use/main.go:49","msg":"new db err","domain":"gin-use[dev]","error":"[db connection failed] Database name: : failed to connect to `host=port= user=password= database=sslmode=disable`: hostname resolving error (lookup port=: no such host)","errorVerbose":"failed to connect to `host=port= user=password= database=sslmode=disable`: hostname resolving error (lookup port=: no such host)\n[db connection failed] Database name: \ngin-use/src/util/db.dbConnect\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/db/postgres.go:83\ngin-use/src/util/db.New\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/db/postgres.go:30\nmain.main\n\t/home/linkai/data/workspace/goWork/src/gin-use/main.go:47\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"}
{"level":"error","time":"2021-06-01 15:00:14","caller":"gin-use/main.go:56","msg":"new cahe err","domain":"gin-use[dev]","error":"ping redis err: dial tcp 127.0.0.1:6379: connect: connection refused","errorVerbose":"dial tcp 127.0.0.1:6379: connect: connection refused\nping redis err\ngin-use/src/util/cache.redisConnect\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/cache/redis.go:71\ngin-use/src/util/cache.New\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/cache/redis.go:47\nmain.main\n\t/home/linkai/data/workspace/goWork/src/gin-use/main.go:54\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"}
{"level":"error","time":"2021-06-01 15:00:16","caller":"gin-use/main.go:49","msg":"new db err","domain":"gin-use[dev]","error":"[db connection failed] Database name: : failed to connect to `host=port= user=password= database=sslmode=disable`: hostname resolving error (lookup port=: no such host)","errorVerbose":"failed to connect to `host=port= user=password= database=sslmode=disable`: hostname resolving error (lookup port=: no such host)\n[db connection failed] Database name: \ngin-use/src/util/db.dbConnect\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/db/postgres.go:83\ngin-use/src/util/db.New\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/db/postgres.go:30\nmain.main\n\t/home/linkai/data/workspace/goWork/src/gin-use/main.go:47\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"}
{"level":"error","time":"2021-06-01 15:00:16","caller":"gin-use/main.go:56","msg":"new cahe err","domain":"gin-use[dev]","error":"ping redis err: dial tcp 127.0.0.1:6379: connect: connection refused","errorVerbose":"dial tcp 127.0.0.1:6379: connect: connection refused\nping redis err\ngin-use/src/util/cache.redisConnect\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/cache/redis.go:71\ngin-use/src/util/cache.New\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/cache/redis.go:47\nmain.main\n\t/home/linkai/data/workspace/goWork/src/gin-use/main.go:54\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"}
{"level":"error","time":"2021-06-01 15:00:31","caller":"gin-use/main.go:49","msg":"new db err","domain":"gin-use[dev]","error":"[db connection failed] Database name: : failed to connect to `host=port= user=password= database=sslmode=disable`: hostname resolving error (lookup port=: no such host)","errorVerbose":"failed to connect to `host=port= user=password= database=sslmode=disable`: hostname resolving error (lookup port=: no such host)\n[db connection failed] Database name: \ngin-use/src/util/db.dbConnect\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/db/postgres.go:83\ngin-use/src/util/db.New\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/db/postgres.go:30\nmain.main\n\t/home/linkai/data/workspace/goWork/src/gin-use/main.go:47\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"}
{"level":"error","time":"2021-06-01 15:00:31","caller":"gin-use/main.go:56","msg":"new cahe err","domain":"gin-use[dev]","error":"ping redis err: dial tcp 127.0.0.1:6379: connect: connection refused","errorVerbose":"dial tcp 127.0.0.1:6379: connect: connection refused\nping redis err\ngin-use/src/util/cache.redisConnect\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/cache/redis.go:71\ngin-use/src/util/cache.New\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/cache/redis.go:47\nmain.main\n\t/home/linkai/data/workspace/goWork/src/gin-use/main.go:54\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"}
{"level":"error","time":"2021-06-01 15:00:36","caller":"gin-use/main.go:49","msg":"new db err","domain":"gin-use[dev]","error":"[db connection failed] Database name: : failed to connect to `host=port= user=password= database=sslmode=disable`: hostname resolving error (lookup port=: no such host)","errorVerbose":"failed to connect to `host=port= user=password= database=sslmode=disable`: hostname resolving error (lookup port=: no such host)\n[db connection failed] Database name: \ngin-use/src/util/db.dbConnect\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/db/postgres.go:83\ngin-use/src/util/db.New\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/db/postgres.go:30\nmain.main\n\t/home/linkai/data/workspace/goWork/src/gin-use/main.go:47\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"}
{"level":"error","time":"2021-06-01 15:00:36","caller":"gin-use/main.go:56","msg":"new cahe err","domain":"gin-use[dev]","error":"ping redis err: dial tcp 127.0.0.1:6379: connect: connection refused","errorVerbose":"dial tcp 127.0.0.1:6379: connect: connection refused\nping redis err\ngin-use/src/util/cache.redisConnect\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/cache/redis.go:71\ngin-use/src/util/cache.New\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/cache/redis.go:47\nmain.main\n\t/home/linkai/data/workspace/goWork/src/gin-use/main.go:54\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"}
{"level":"error","time":"2021-06-01 15:00:39","caller":"gin-use/main.go:49","msg":"new db err","domain":"gin-use[dev]","error":"[db connection failed] Database name: : failed to connect to `host=port= user=password= database=sslmode=disable`: hostname resolving error (lookup port=: no such host)","errorVerbose":"failed to connect to `host=port= user=password= database=sslmode=disable`: hostname resolving error (lookup port=: no such host)\n[db connection failed] Database name: \ngin-use/src/util/db.dbConnect\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/db/postgres.go:83\ngin-use/src/util/db.New\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/db/postgres.go:30\nmain.main\n\t/home/linkai/data/workspace/goWork/src/gin-use/main.go:47\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"}
{"level":"error","time":"2021-06-01 15:00:39","caller":"gin-use/main.go:56","msg":"new cahe err","domain":"gin-use[dev]","error":"ping redis err: dial tcp 127.0.0.1:6379: connect: connection refused","errorVerbose":"dial tcp 127.0.0.1:6379: connect: connection refused\nping redis err\ngin-use/src/util/cache.redisConnect\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/cache/redis.go:71\ngin-use/src/util/cache.New\n\t/home/linkai/data/workspace/goWork/src/gin-use/src/util/cache/redis.go:47\nmain.main\n\t/home/linkai/data/workspace/goWork/src/gin-use/main.go:54\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"}
